SET PROCEDURE TO C:\FWSU\prg\CLASSLIQ
SET CLASSLIB TO C:\FWSU\CLASES\RH
SET EXCLUSIVE OFF
SET DELETED ON
CLOSE TABLES all
*SET PATH TO c:\suerut\empre1
x=CREATEOBJECT('configurar')
rh = CREATEOBJECT('legajoper')
SELECT  S.LEGAJO,P.NOMBRE,P.DEPART,S.CONCEPTO,S.CANTIDAD FROM 32018 AS S;
INNER JOIN PERSONAL AS P ON S.LEGAJO = P.LEGAJO WHERE CONCEPTO =20 .OR. CONCEPTO = 4 ORDER BY P.LEGAJO