SET PROCEDURE TO C:\FWSU\prg\CLASSLIQ
SET EXCLUSIVE OFF
SET DELETED ON
CLOSE TABLES all
*SET PATH TO c:\suerut\empre1
x=CREATEOBJECT('configurar')
x.Seteopat(1)
fso = CreateObject('Scripting.FileSystemObject')
tf = fso.CreateTextFile('c:\sueldos\ls.txt', .t.)
tf.close


*DIMENSION LEGAJOS[10]

*LEGAJOS[1]=441
*LEGAJOS[2]=442
*LEGAJOS[3]=444
*LEGAJOS[4]=445
*LEGAJOS[5]=448
*LEGAJOS[6]=449
*LEGAJOS[7]=465
*LEGAJOS[8]=484
*LEGAJOS[9]=487
*LEGAJOS[10]=525

*SELECT legajo,nombre,depart, legajo=0 as marca FROM personal WHERE activo = "A" ORDER BY depart;
INTO TABLE F:\SUELDOS\EMPRE1\listafp
CLEAR
USE listafp
DELETE FOR LEGAJO= 819
REPLACE ALL MARCA WITH .F.
LOCATE FOR LEGAJO = 864
SKIP
FOR IND = 1 TO 25
    REPLACE MARCA WITH .T.
    SKIP

NEXT
*BROWSE FOR LEGAJO > 809

VarCont = 1
SCAN FOR MARCA = .T.
      ?LEGAJO
      
      *DO EXCELLIBROB WITH LISTAFP.LEGAJO,VarCont
      VarCont= VarCont+1

ENDSCAN





