SET DEFAULT TO C:\SUERUT\EMPRE1
SET DELETED ON
SELECT * FROM SUE3 ORDER BY SECCION,CHAPA
SELECT * FROM SUE3 ORDER BY SECCION,CHAPA
SELECT SUE3
USE
SELECT * FROM SUE3 ORDER BY SECCION,CHAPA INTO CURSOR ST
SELECT SUE3
USE
SELECT * FROM ST INTO CURSOR SUE3
REPORT FORM ASIENTO2
REPORT FORM ASIENTO2 PREVIEW
