SET EXCLUSIVE OFF
SET DELETED ON
SET PROCEDURE TO C:\FWSU\prg\CLASSLIQ
SET CLASSLIB TO C:\FWSU\CLASES\RH


*SET PATH TO c:\suerut\empre1
x=CREATEOBJECT('configurar')
x.Seteopat(1)
clear
SELECT tabhoras
GO top
SCAN tabhoras
   ?TABHORAS.LEG
   *DELETE FROM 122019 WHERE legajo = .leg .and. liquida = 3
   
   UPDATE MAPER SET UNIDADES  = TABHORAS.COMIDA WHERE LEGAJO = TABHORAS.LEG .AND. TIPOLIQ = 3 .AND. CONCEPTO = 59
   UPDATE MAPER SET UNIDADES  = TABHORAS.COMIDA WHERE LEGAJO = TABHORAS.LEG .AND. TIPOLIQ = 3 .AND. CONCEPTO = 64
   
   DO liquidacion-automatica
   SELECT tabhoras
ENDSCAN
