SET PATH TO F:\SUELDOS\EMPRE1;C:\SUERUT\CONSULTAS
SET EXCLUSIVE OFF
SET DELETED ON
ARCHIVO = "122018"
PUBLIC mes as String
mes = "DICIEMBRE-2018"
SELECT LEGAJO, NOMBRE,CUIL,SINDICATO FROM PERSONAL WHERE SINDICATO = "SIND CHOF ENTRE RIOS     " .AND. ACTIVO = "A";
INTO CURSOR LIS
SELECT LEGAJO,SUM(IIF(CONCEPTO = 1,APORTE,0))AS BASICO,SUM(IIF(CONCEPTO = 87.OR.CONCEPTO = 870,DESCUENTO,0))AS SDCATO,; 
SUM(IIF(CONCEPTO =114,DESCUENTO,0))AS MUTUAL, SUM(APORTE)as bruto ,SUM(SINAPORTE)as nre FROM &ARCHIVO  GROUP BY LEGAJO INTO CURSOR SUELDO
SELECT LIS.NOMBRE,LIS.CUIL,SUELDO.BRUTO,SUELDO.SDCATO,SUELDO.MUTUAL FROM SUELDO INNER JOIN LIS ON LIS.LEGAJO = SUELDO.LEGAJO INTO CURSOR LSD 
REPORT FORM lsidcanterios TO PRINTER PROMPT











