SET PROCEDURE TO c:\fwsu\prg\classliq
ob = CREATEOBJECT("configurar")
ob.Seteopat(1)

SELECT LEGAJO,NOMBRE,FECHAING,FECHABAJA FROM PERSONAL WHERE ACTIVO = "A" .AND. FECHAING <= CTOD("01-10-2020") .AND. CATEGORIA <> "DIRECTOR" .AND. LEGAJO <> 819 .AND. LEGAJO <> 810;
INTO CURSOR LISTADOACUER
*SELECT LEGAJO,NOMBRE,FECHAING FROM PERSONAL WHERE ACTIVO = "A" .AND. CATEGORIA <> "DIRECTOR" INTO CURSOR LISTADOACUER


SCAN
    SELECT CONCEPTO FROM 32021 WHERE CONCEPTO = 451 .AND. LIQUIDA = 1 .AND. LEGAJO = LISTADOACUER.LEGAJO;
    INTO CURSOR EXISTE	
    
    IF EOF()
       INSERT INTO 32021 (LEGAJO,CONCEPTO,DESCRIP,SINAPORTE,LIQUIDA) VALUES (LISTADOACUER.LEGAJO,451,"Asig .Extraord. cta 2",6250,1)
    ELSE 
       UPDATE 32021 SET DESCRIP = "Asig.Extra. cta 2" ;
       WHERE LIQUIDA = 1 .AND. LEGAJO = LISTADOACUER.LEGAJO
    
       
    ENDIF
    
    SELECT LISTADOACUER




ENDSCAN



CLOSE TABLES ALL