SET PROCEDURE TO c:\fwsu\prg\classliq
ob = CREATEOBJECT("configurar")
ob.Seteopat(1)

SELECT LEGAJO,NOMBRE,FECHAING FROM PERSONAL WHERE ACTIVO = "A" .AND. FECHAING <= CTOD("03-09-2019") .AND. CATEGORIA <> "DIRECTOR";
INTO CURSOR LISTADOACUER
*SELECT LEGAJO,NOMBRE,FECHAING FROM PERSONAL WHERE ACTIVO = "A" .AND. CATEGORIA <> "DIRECTOR" INTO CURSOR LISTADOACUER




SCAN
    SELECT CONCEPTO FROM 42020 WHERE CONCEPTO = 448 .AND. LIQUIDA = 1 .AND. LEGAJO = LISTADOACUER.LEGAJO;
    INTO CURSOR EXISTE	
    
    IF EOF()
       INSERT INTO 42020 (LEGAJO,CONCEPTO,DESCRIP,SINAPORTE,LIQUIDA) VALUES (LISTADOACUER.LEGAJO,448,"Bono No Rem Cta 4",5000,1)
    ELSE 
       UPDATE 42020 SET DESCRIP = "Bono No Rem Cta 4" ;
       WHERE LIQUIDA = 1 .AND. LEGAJO = LISTADOACUER.LEGAJO
    
       
    ENDIF
    
    SELECT LISTADOACUER




ENDSCAN

CLOSE TABLES ALL